context:
  name: mediainfo
  version: "25.03"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/MediaArea/MediaInfo/archive/refs/tags/v${{ version }}.tar.gz
  sha256: "a03490cddb72840882600bde4d0b9c329e4ef3d4f37a2aeed59720bb93498283"

build:
  skip: win
  script:
    content: |
      pushd Project/GNU/CLI
      autoreconf -fi
      ./configure --prefix="$PREFIX" || (cat config.log && false)
      make install
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - pkg-config
    - autoconf
    - libtool
    - automake
    - make
  host:
    - libmediainfo ${{ version }}.*
    - libzen
    - zlib

tests:
  - script: mediainfo --help
  - package_contents:
      files:
        - bin/mediainfo

about:
  homepage: https://mediaarea.net/MediaInfo
  summary: Convenient unified display of the most relevant technical and tag data for video and audio files
  description: |
    MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - License.html
  documentation: https://mediaarea.net/MediaInfo
  repository: https://github.com/MediaArea/MediaInfo

extra:
  recipe-maintainers:
    - pavelzw
