context:
  name: mediainfo
  version: "25.04"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  # repo contains symlinks which is hard to handle if we use tarball or zip.
  - git: https://github.com/MediaArea/MediaInfo
    # v25.04
    rev: '8fb5f2180acf4d417bb4ad1eabeec63f5950b0b7'
  - path: ./build/

build:
  script:
    content:
      - if: unix
        then: |
          pushd Project/GNU/CLI
          autoreconf -fi
          ./configure --prefix="$PREFIX" || (cat config.log && false)
          make install
        else: |
          cmake . -B build %CMAKE_ARGS% -G Ninja

          ninja -v -C build install

  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - if: unix
      then:
        - pkg-config
        - autoconf
        - libtool
        - automake
        - make
      else:
        - cmake
        - ninja
  host:
    - libmediainfo ${{ version }}.*
    - libzen
    - zlib

tests:
  - script: mediainfo --help
  - package_contents:
      files:
        - bin/mediainfo

about:
  homepage: https://mediaarea.net/MediaInfo
  summary: Convenient unified display of the most relevant technical and tag data for video and audio files
  description: |
    MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - License.html
  documentation: https://mediaarea.net/MediaInfo
  repository: https://github.com/MediaArea/MediaInfo

extra:
  recipe-maintainers:
    - pavelzw
