context:
  name: mediainfo
  version: "25.09"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  # repo contains symlinks which is hard to handle if we use tarball or zip.
  - if: win
    then:
      path: ./build/
    else:
      url: https://github.com/MediaArea/MediaInfo/archive/refs/tags/v${{ version }}.tar.gz
      sha256: "b8db8beb64b22f87e5110564fb965d8c9d53ce3de6977c814749b371ecb7419c"
      target_directory: src

build:
  script:
    content:
      - if: unix
        then: |
          pushd src/Project/GNU/CLI
          autoreconf -fi
          ./configure --prefix="$PREFIX" || (cat config.log && false)
          make install

        # repo contains symlinks which is hard to handle if we use tarball or zip.
        # use source.url after rattler-build/issues/1671 is fixed
        else: |
          git clone https://github.com/MediaArea/MediaInfo.git src --branch v${{ version }} --depth 1 --config core.symlinks=false

          cmake . -B build %CMAKE_ARGS% -G Ninja

          ninja -v -C build install

  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - pkg-config

    - if: unix
      then:
        - autoconf
        - libtool
        - automake
        - make
      else:
        - cmake
        - ninja
  host:
    - libmediainfo ${{ version }}.*
    - libzen
    - zlib

tests:
  - script: mediainfo --help
  - package_contents:
      bin:
        - mediainfo

about:
  homepage: https://mediaarea.net/MediaInfo
  summary: Convenient unified display of the most relevant technical and tag data for video and audio files
  description: |
    MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
  license: BSD-2-Clause
  license_file:
    - src/LICENSE
    - src/License.html
  documentation: https://mediaarea.net/MediaInfo
  repository: https://github.com/MediaArea/MediaInfo

extra:
  recipe-maintainers:
    - pavelzw
