context:
  name: mediainfo
  version: "25.04"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  # repo contains symlinks which is hard to handle if we use tarball or zip.
  - url: https://github.com/trim21/MediaInfo/archive/refs/heads/wip.zip
    sha256: "250454c63a83c5d4d6cb2a0f66bdb23c17d94d5860685554a5fa1cdcfb4778de"
    # filter:
    #   exclude:
    #     - Project/OBS/**
    #     - Project/debian/**
  - path: ./build/

build:
  script:
    content:
      - if: unix
        then: |
          pushd Project/GNU/CLI
          autoreconf -fi
          ./configure --prefix="$PREFIX" || (cat config.log && false)
          make install
        else: |
          cmake . -B build %CMAKE_ARGS% -G Ninja

          ninja -v -C build install

  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - pkg-config

    - if: unix
      then:
        - autoconf
        - libtool
        - automake
        - make
      else:
        - cmake
        - ninja
  host:
    - libmediainfo ${{ version }}.*
    - libzen
    - zlib
    - tinyxml2

tests:
  - script: mediainfo --help
  - package_contents:
      bin:
        - mediainfo

about:
  homepage: https://mediaarea.net/MediaInfo
  summary: Convenient unified display of the most relevant technical and tag data for video and audio files
  description: |
    MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - License.html
  documentation: https://mediaarea.net/MediaInfo
  repository: https://github.com/MediaArea/MediaInfo

extra:
  recipe-maintainers:
    - pavelzw
